apiVersion: apps/v1
kind: Deployment

metadata:
  name: notes-app-deployment
  namespace: nginx

spec:
  replicas: 2

  selector:
    matchLabels:
      app: notes-app

  template:
    metadata:
      labels:
        app: notes-app

    spec:
      containers:
        - name: notes-app-container
          image: hussnainashiq56/notes-app-image
          ports:
            - containerPort: 8000
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 200m
              memory: 256Mi
          livenessProbe:
            httpGet:
              path: /
              port: 8000
          readinessProbe:
            httpGet:
              path: /
              port: 8000
